server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: ${CUSTOMER_DB_URL:jdbc:postgresql://localhost:5432/devsu_db?currentSchema=customer_service}
    username: ${CUSTOMER_DB_USERNAME:devsu}
    password: ${CUSTOMER_DB_PASSWORD:devsu}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: customer_service
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  messaging:
    customer-events:
      exchange: ${CUSTOMER_EVENTS_EXCHANGE:customer.events}
      routing-key: ${CUSTOMER_EVENTS_ROUTING_KEY:customer.events}
